// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bouptqqlegpwwxtvttqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJvdXB0cXFsZWdwd3d4dHZ0dHFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5MjExOTcsImV4cCI6MjA1MjQ5NzE5N30.mb_w-sRxT0ZEVepXmLrzRvrwRPBIoIY_Fkp-XX7lCxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);